use_frameworks!

platform :ios, '9.0'

target 'SwiftUICarousel_Example' do
  pod 'SwiftUICarousel', :path => '../'

  target 'SwiftUICarousel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
